name = "TransformSpecifications"
uuid = "b92eaff8-8912-4b32-ad24-14d7c692d780"
authors = ["Beacon Biosignals, Inc"]
version = "0.0.1"

[compat]
Aqua = "0.6"
julia = "1.7.2"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Aqua", "Test"]
